### ISSUE TITLE
Re-work go module and version tags

### ISSUE THREAD

**Issue by belak** [go-irc/irc#69]
The main reason for this is that I strongly dislike importing this package as github.com/go-irc/irc/v2 and would like most of my tooling to recognize the import name properly. Additionally, I don't think this library is (currently) important enough for this to cause an issue in any packages other than mine. If you import from github.com/go-irc/irc this package will continue to work and as go module support is experimental, I don't have many qualms about temporarily breaking support.

Alternatively, if I could keep the current version tags and import this as github.com/go-irc/irc, that would be fine.

Related to #68. I plan on re-working tags and changing the module to the base path. As this library is not 100% stable, I plan on remapping the tags as follows:

```
v1.0.0 -> v0.1.0
v1.0.1 -> v0.1.1
v1.1.0 -> v0.1.2
v1.2.0 -> v0.1.3
v1.3.0 -> v0.1.4
v2.0.0 -> v0.2.0
v2.1.0 -> v0.2.1
v2.1.1 -> v0.2.2
v2.1.2 -> v0.2.3
```

Here are the current tags, for reference:

```
f5d8d856b31995567b637d6f8eaa78ae2e0f9206 refs/tags/v1.0.0
762af81012744b1461f57d414b82f3ae9a9c5b99 refs/tags/v1.0.1
f23d78362d188e111f34ce5db305cc53e7f1b932 refs/tags/v1.1.0
acbcebe1cd4c60fe20fd3a5a3d64accd53058f2e refs/tags/v1.2.0
a56998ff69437c015617474a7eaf3b0f6bb92b9e refs/tags/v1.3.0
01e72ff44254c3a85e6544295da4ce04be23c356 refs/tags/v2.0.0
29f1845f11cf8b48016865be7381299056393f72 refs/tags/v2.1.0
02e1ea193747d24d87b484473511ce0e4356946c refs/tags/v2.1.1
4901bf6be124ba1558d3657e91286393c97fb47f refs/tags/v2.1.2
```

**Comment by myitcv** [comment]
Is there a reason you chose not to define the v2 series as `module gopkg.in/irc.v2`?

**Comment by belak** [comment]
This has been fixed by defining the package as `gopkg.in/irc.v3`. I was trying to avoid using that because it's always seemed a bit silly to me that go modules break the concept that a module is a folder in a repository but I think there's no avoiding it now.

Previously, this package was importable as gopkg.in/irc.v2 if you wanted a stable version and github.com/go-irc/irc if you wanted to always track the HEAD of master but I don't think there's a way to do that with modules
