### ISSUE TITLE
Changes for v4

### ISSUE THREAD

**Issue by belak** [go-irc/irc#78]
Hello all!

I've been looking at releasing v4 of this library, mostly as a slightly simpler version and splitting some utilities I keep having to make out into a separate `ircx` package. I wanted to run all these past people before I just go ahead and do them though.

- Move client out to `ircx` - the idea is to keep the base package to only protocol-related tools like reading and writing messages, numerics, etc.
- Change the import path to `gopkg.in/go-irc/irc.v4` - this will allow us to also have `gopkg.in/go-irc/ircx.v0` rather than `gopkg.in/irc.v4` and the longer form for `ircx`
- Taking a look at better context support for Conn. Potentially seeing if there's a good way to handle a Write with a timeout.

Additional tools meant for ircx:

- Client - I have some ideas for better Context support
- ISupport parsing/tools
- Some form of tracker which allows you to track which channels you're in, what their topics are, and what nicks are in each channel. I could potentially add user mode tracking as well.

Does anyone have any thoughts?

**Comment by danopia** [comment]
As long as the original 'building block' base is available at some path, that should be generally agreeable, the subpath doesn't seem troublesome. It makes sense to have a 'reference implementation' of sorts for people wanting somewhat more work done for them.

One thing I'd love to see in a new major version is either first-class SASL support, or at least the necessary reworkings to allow hooking the registration flow so we can perform the SASL dance ourselves (https://github.com/go-irc/irc/issues/57#issuecomment-379926246). Not having support for 'properly' logging into servers has been a papercut for my general use client.

For prior art&mdash;another go client which supports both `PLAIN` and `EXTERNAL` (certfp) SASL has a [SASLMech interface](https://github.com/lrstanley/girc/blob/master/cap_sasl.go#L12-L31) with two default types, you can just slot one instance into the connection configuration. Not sure if that level of support would be more `irc` or `ircx` under your v4 blueprint.

**Comment by belak** [comment]
Yep, I plan on leaving Conn, Reader, Writer, Event, and Prefix mostly untouched. SASL would fit in the ircx package. I'll have to check out that implementation and see if I can come up with anything.

**Comment by belak** [comment]
I had a bit of time so I started work on this.

Unfortunately, it doesn't look like gopkg.in handles alpha versions, so I'm temporarily moving this library back to the github namespace until it actually gets merged in. At that point, it will most likely go back to gopkg.in. For now the import paths are as follows:

- github.com/go-irc/irc/v4
- github.com/go-irc/ircx

Things that have been done so far:

- ircx package has been created
- The semi-hacky API for Conn.WriteCallback has been made public so the Client can live in another package
- Client has been moved into ircx
- ISupportTracker has been ported from another project of mine
- Basic channel tracker has been ported from another project of mine
- Some simple tweaks to Conn to add a Close method, so if you're wrapping it, it's a little easier - I may back out of this one since it seems a little weird to require a ReadWriteCloser just to export a Close method when a ReadWriter will do

And this is where I semi-rant about Go package management... I really wish that suffix wasn't required. It's really frustrating needing to add /v4 for v2+ but not for v0 and v1. It's a small, but fairly frustrating thing. I know the problem it's trying to solve... and I get it... but man, I really don't like those import paths.

**Comment by belak** [comment]
Things left to do:

- SASL
- Tests for ISupport
- Tests for Tracker
- Context support
- Fixing CI - we seem to be running into https://github.com/actions-contrib/golangci-lint/issues/11 - I may look at tweaking it a bit and using a custom version so we can get the github-actions output, but we'll have to see... I'd expect that stuff to make it upstream eventually.

**Comment by belak** [comment]
I'm actually re-thinking this - I'm in the progress of moving Client back from ircx, and adding Tracker/ISupport under a new release. If/when breaking changes happen (like improved context support) I will do a major version bump.

**Comment by belak** [comment]
I don't have the time to work on improved Context support at the moment, so I'm going to leave that for v5.

**Comment by belak** [comment]
v4.0.0 was merged and tagged!
