### ISSUE TITLE
Drop TagValue

### ISSUE THREAD

**Issue by emersion** [go-irc/irc#83]
Would you consider dropping the `TagValue` type so that the `Tags` type can just be `map[string]string`? That would avoid unnecessary conversions between `TagValue` and `string` when accessing or updating tags.

**Comment by belak** [comment]
Yeah, this seems like a reasonable change - thankfully I haven't released v4 yet, so I can still make these tweaks

**Comment by belak** [comment]
Fixed in 7ba1a18. Thanks for the suggestion!
