### ISSUE TITLE
Scheduling recurring function calls

### ISSUE THREAD

**Issue by nathanvy** [go-irc/irc#86]
Hello,

I'm using this package for a side project, so first of all thank you for providing it!

I'd like to hack on my local copy and add the capability to call an arbitrary function on a recurring/scheduled basis (using e.g. time.Tickers) to do things like announce to channels and also to poll GPIO devices at regular intervals and present the results on IRC.  But it's not immediately clear to me where would be the best place to add this.  Would it be better...

1. Define a function similar to `maybeStartPingLoop()` and call it from `RunContext()`? or...
2. Edit the loop in `startReadLoop()` and call scheduled function calls there?

Or is there a better approach?  I'm still kinda feeling my way around Go, coming from C#.

Thanks!

**Comment by nathanvy** [comment]
Well I have a working patch so I'll create a PR in case anyone is interested.

**Comment by belak** [comment]
Hi, thanks for posting! I've been purposefully keeping go-irc fairly minimal so I'm not sure how likely this feature would be to make it into core, but I've got an example below which does pretty much the same thing without modifying the framework. If you've got any questions, I'd be happy to answer them.

```
package main

import (
	"sync"
	"log"

	"gopkg.in/irc.v3"
)

func main() {
	// sync.Once allows you to create a container which will track when it's
	// been called - it's generally used for initialization, so it's helpful
	// here.
	var tickStarter sync.Once

	// Using a cancellable context allows us to cancel the connection outside a
	// connection error. This is also what allows us to use ctx.Done() later to
	// roughly track when the connection is done.
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	// TODO: insert conn here, rather than nil
	c := NewClient(nil, irc.ClientConfig{
		Handler: HandlerFunc(func(c *irc.Client, m *irc.Message) {
			log.Printf("Got Message: %+v\n", m)

			// "001" is also known as RPL_WELCOME - every compliant server I'm
			// aware of sends this when the user has successfully connected. This
			// should only be sent once, but we use the sync.Once to ensure we only
			// start the tickers once.
			if m.Command == "001" {
				// Here we use the sync.Once we created earlier to fire off our
				// tickers in the background. It's helpful to do this in the
				// Handler because you have access to the Client.
				tickStarter.Do(func() {
					go func() {
						// Fairly standard ticker code
						ticker := time.NewTicker(30 * time.Second)
						defer ticker.Stop()

						for {
							select {
							case <-ticker.C:
								_ = c.Writef("PRIVMSG #some-channel :I ticked!")
							case <-ctx.Done():
								log.Println("Closing ticker")
								return
							}
						}
					}()
				})
			}
		}),
	})

	err := c.RunContext(ctx)
	if err != nil {
		log.Print(err.Error())
		return
	}
}
```

**Comment by nathanvy** [comment]
Thanks. Your example will hopefully be of use to someone; it's well written and you should put it in the documentation!

As for me I think I'm going to rewrite in a better language that has sane packaging. I'm not interested in wrestling with Go any more, and rewriting from scratch in C# or Lisp or something will probably take less time than figuring out how to make go not choke on a package with a version greater than 1.

**Comment by belak** [comment]
Fair enough! Best of luck with your project! Either, way thanks for reaching out - better examples are one thing I really could provide.

On a side note, if you ever have any questions about the IRC protocol itself (there are definitely a few "gotchas", https://modern.ircdocs.horse is a great resource, despite the strange URL. Also, a number of people who know the protocol forwards and backwards hang out in #botters and #ircdocs on Libera.
